### ISSUE TITLE
Missing reference for `tosca.capabilities.EndPoint` in CSAR export

### ISSUE THREAD

**Issue by duelle** [radon-h2020/radon-gmt#22]
After extracting the attached [JMeterMasterOnly.zip](https://github.com/radon-h2020/radon-gmt/files/4488390/JMeterMasterOnly.zip) file and fixing the namespaces (#21) and running `opera deploy radonblueprintstesting__JMeterMasterOnly.tosca` in the `_definitions` folder, Opera reports an error `radonnodesdocker__DockerApplication.tosca:19:23: [ReferenceWrapper] Invalid reference capability_types/tosca.capabilities.EndPoint`.

When adding a separately exported definition of it ([toscacapabilities__Endpoint.txt](https://github.com/radon-h2020/radon-gmt/files/4488423/toscacapabilities__Endpoint.txt)) and adding it to the imports, the following error is reported `STD[v_1_3]:46:3: [MapWrapper] Duplicate keys 'tosca.capabilities.Endpoint' found in STD[v_1_3]:46:3 and radoncapabilitiescontainer__DockerRuntime.tosca:4:3`.

When adding a custom section to the end of the `radoncapabilitiescontainer__DockerRuntime.tosca` definition, no errors are reported:
```
tosca.capabilities.EndPoint:
    derived_from: tosca.capabilities.Container
    properties:
      name:
        type: list
        required: false
        status: supported
```

Is a definition missing in the export or is this a parsing issue on the side of Opera?
