### ISSUE TITLE
Signle-line relationship reference in TOSCA Reqirements

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-gmt#3]
The reference to the relationship TOSCA requirements should be done in single line without "type" word. Currently, the CSAR export includes:

```
      requirements:
        - host:
            node: AwsPlatform
            relationship:
              type: con_HostedOn_0
            capability: host
```

The correct way would be:

```
      requirements:
        - host:
            node: AwsPlatform
            relationship: con_HostedOn_0
            capability: host

```

The diff is also shown in a figure:
![2020-03-09 14_52_11-WinMerge -  radonblueprints__ToyExample tosca x 2](https://user-images.githubusercontent.com/2518386/76219428-205d2800-6216-11ea-8483-1aafebc39a66.png)
