### ISSUE TITLE
Policies in service templates are serialized not as a list

### ISSUE THREAD

**Issue by miwurster** [radon-h2020/radon-gmt#47]
According to 3.9.2 in the [TOSCA spec](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/TOSCA-Simple-Profile-YAML-v1.3.html), policies in a service template must be serialized as a list of policy definitions. Like in this example:
```
policies:
    - my_anti_collocation_policy:
        type: my.policies.anticolocateion
        targets: [ my_co_location_group ]
        # For this example, specific policy definitions are considered
        # domain specific and are not included here
```

Currently, Winery serializes policies in a map.
